package ro.ubb.socket.common.infrastructure;

public class MessageHeader {
  public static final String ASSIGNMENT_ADD = "ASSIGNMENT_ADD",
      ASSIGNMENT_ALL = "ASSIGNMENT_ALL",
      ASSIGNMENT_SORTED = "ASSIGNMENT_SORTED",
      ASSIGNMENT_BY_ID = "ASSIGNMENT_BY_ID",
      ASSIGNMENT_DELETE = "ASSIGNMENT_DELETE",
      ASSIGNMENT_UPDATE = "ASSIGNMENT_UPDATE",
      ASSIGNMENT_GREATEST_MEAN = "ASSIGNMENT_GREATEST_MEAN",
      ASSIGNMENT_PROBLEM_MOST_ASSIGNED = "ASSIGNMENT_PROBLEM_MOST_ASSIGNED",
      ASSIGNMENT_AVERAGE_GRADE = "ASSIGNMENT_AVERAGE_GRADE",
      ASSIGNMENT_PROBLEM_MAPPING = "ASSIGNMENT_PROBLEM_MAPPING",
      STUDENT_ADD = "STUDENT_ADD",
      STUDENT_ALL = "STUDENT_ALL",
      STUDENT_SORTED = "STUDENT_SORTED",
      STUDENT_BY_ID = "STUDENT_BY_ID",
      STUDENT_DELETE = "STUDENT_DELETE",
      STUDENT_UPDATE = "STUDENT_UPDATE",
      LABPROBLEM_ADD = "LABPROBLEM_ADD",
      LABPROBLEM_ALL = "LABPROBLEM_ALL",
      LABPROBLEM_SORTED = "LABPROBLEM_SORTED",
      LABPROBLEM_BY_ID = "LABPROBLEM_BY_ID",
      LABPROBLEM_DELETE = "LABPROBLEM_DELETE",
      LABPROBLEM_UPDATE = "LABPROBLEM_UPDATE",
      OK_REQUEST = "OK_REQUEST",
      BAD_REQUEST = "BAD_REQUEST",
      SERVER_SHUTDOWN = "SERVER_SHUTDOWN";
}
